Document: couchfuse
Title: Debian couchfuse Manual
Author: <insert document author here>
Abstract: This manual describes what couchfuse is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/couchfuse/couchfuse.sgml.gz

Format: postscript
Files: /usr/share/doc/couchfuse/couchfuse.ps.gz

Format: text
Files: /usr/share/doc/couchfuse/couchfuse.text.gz

Format: HTML
Index: /usr/share/doc/couchfuse/html/index.html
Files: /usr/share/doc/couchfuse/html/*.html
